### ISSUE TITLE
Сould not find source file

### ISSUE THREAD

**Issue by esykai** [DuckyC/gm_dotnet#3]
![image](https://user-images.githubusercontent.com/45533799/73935372-6c543e80-48f1-11ea-8cd9-2e74f1b6b029.png)

How to solve this problem?

**Comment by sbarisic** [comment]
You are missing sources in gm_dotnet/GSharp/Libraria folder because it's a submodule

https://github.com/sbarisic/Libraria/tree/b15e4da414f2fc289acf0bc7f9e4a4106e0dc61c

Download this and extract to Libraria directory and it should work

**Comment by esykai** [comment]
Oh, many thanks.
